"""
Utility script to read and display MessagePack symbol data.

This script reads the MessagePack binary file generated by mt5_symbol_retriever.py
and provides various viewing options.
"""

import msgpack
import json
from pathlib import Path
import os
from typing import Dict, Optional


def get_utils_dir():
    """Return the absolute path to the utils directory (where this script and msgpack file are)."""
    return Path(__file__).parent.resolve()


class MessagePackReader:
    """Reads and displays MessagePack symbol data."""

    def __init__(self, filename: str = "mt5_symbols.msgpack"):
        utils_dir = get_utils_dir()
        self.filename = str(Path(utils_dir) / filename)
        self.data: Optional[Dict] = None

    def load(self) -> bool:
        """
        Load MessagePack file from the utils directory.

        Returns:
            bool: True if successful, False otherwise
        """
        if not Path(self.filename).exists():
            print(f"[ERROR] File not found: {self.filename}")
            return False

        try:
            with open(self.filename, 'rb') as f:
                self.data = msgpack.unpack(f, raw=False)

            file_size = Path(self.filename).stat().st_size
            print(f"[SUCCESS] Loaded {self.filename}")
            print(f"[INFO] File size: {file_size:,} bytes ({file_size / 1024:.2f} KB)")
            return True

        except Exception as e:
            print(f"[ERROR] Failed to load MessagePack file: {e}")
            return False

    def display_summary(self):
        """Display summary statistics."""
        if not self.data:
            print("[ERROR] No data loaded")
            return

        metadata = self.data["metadata"]
        stats = metadata["statistics"]

        print("\n" + "=" * 60)
        print("SYMBOL DATA SUMMARY")
        print("=" * 60)
        print(f"Generated: {metadata['generated_at']}")
        print(f"Total Symbols: {metadata['total_symbols']}")

        print("\n=== Categories ===")
        for category, subcategories in stats.items():
            print(f"\n{category}:")
            for subcategory, count in subcategories.items():
                print(f"  {subcategory}: {count}")

    def display_category(self, category: str, subcategory: Optional[str] = None):
        """
        Display symbols from a specific category.

        Args:
            category: Category name (e.g., "Forex", "Crypto")
            subcategory: Optional subcategory (e.g., "Major", "BTC")
        """
        if not self.data:
            print("[ERROR] No data loaded")
            return

        symbols = self.data.get("symbols", {})

        if category not in symbols:
            print(f"[ERROR] Category '{category}' not found")
            print(f"Available categories: {', '.join(symbols.keys())}")
            return

        category_data = symbols[category]

        if subcategory:
            if subcategory not in category_data:
                print(f"[ERROR] Subcategory '{subcategory}' not found in '{category}'")
                print(f"Available subcategories: {', '.join(category_data.keys())}")
                return

            print(f"\n=== {category} - {subcategory} ===")
            for symbol in category_data[subcategory]:
                print(f"  {symbol['name']}: {symbol['description']}")
        else:
            print(f"\n=== {category} (All Subcategories) ===")
            for subcat, symbol_list in category_data.items():
                print(f"\n{subcat}:")
                for symbol in symbol_list:
                    print(f"  {symbol['name']}: {symbol['description']}")

    def export_to_json(self, output_filename: str = "mt5_symbols_from_msgpack.json"):
        """
        Export MessagePack data to JSON for readability.

        Args:
            output_filename: Output JSON filename
        """
        if not self.data:
            print("[ERROR] No data loaded")
            return

        # Ensure output is also in the utils directory for clarity
        utils_dir = get_utils_dir()
        output_path = Path(utils_dir) / output_filename
        with open(output_path, 'w', encoding='utf-8') as f:
            json.dump(self.data, f, indent=2, ensure_ascii=False)

        file_size = output_path.stat().st_size
        print(f"[SUCCESS] Exported to {output_path}")
        print(f"[INFO] JSON file size: {file_size:,} bytes ({file_size / 1024:.2f} KB)")

    def search_symbol(self, search_term: str):
        """
        Search for symbols containing the search term.

        Args:
            search_term: Symbol name or description to search for
        """
        if not self.data:
            print("[ERROR] No data loaded")
            return

        search_term = search_term.upper()
        symbols_data = self.data.get("symbols", {})
        found = []

        for category, subcategories in symbols_data.items():
            for subcategory, symbol_list in subcategories.items():
                for symbol in symbol_list:
                    if (search_term in symbol['name'].upper() or 
                        search_term in symbol['description'].upper()):
                        found.append({
                            'category': category,
                            'subcategory': subcategory,
                            'symbol': symbol
                        })

        if not found:
            print(f"[INFO] No symbols found matching '{search_term}'")
            return

        print(f"\n=== Search Results for '{search_term}' ===")
        print(f"Found {len(found)} symbol(s):\n")

        for item in found:
            symbol = item['symbol']
            print(f"{symbol['name']} ({item['category']} - {item['subcategory']})")
            print(f"  Description: {symbol['description']}")
            if symbol.get('base_currency') and symbol.get('quote_currency'):
                print(f"  Pair: {symbol['base_currency']}/{symbol['quote_currency']}")
            print(f"  Digits: {symbol['digits']}")
            print()


def main():
    """Main execution function."""
    print("=" * 60)
    print("MessagePack Symbol Data Reader")
    print("=" * 60)

    utils_dir = get_utils_dir()
    default_msgpack_path = Path(utils_dir) / "mt5_symbols.msgpack"

    reader = MessagePackReader(str(default_msgpack_path))

    if not reader.load():
        return

    # Display summary
    reader.display_summary()

    # Interactive mode
    print("\n" + "=" * 60)
    print("COMMANDS:")
    print("  summary                    - Display summary")
    print("  category <name>            - Display category (e.g., 'category Forex')")
    print("  subcategory <cat> <subcat> - Display specific subcategory")
    print("  search <term>              - Search for symbols")
    print("  export                     - Export to JSON")
    print("  quit                       - Exit")
    print("=" * 60)

    while True:
        try:
            command = input("\nEnter command (or 'quit'): ").strip()

            if not command or command.lower() == 'quit':
                break

            parts = command.split(maxsplit=2)
            cmd = parts[0].lower()

            if cmd == "summary":
                reader.display_summary()

            elif cmd == "category" and len(parts) >= 2:
                reader.display_category(parts[1])

            elif cmd == "subcategory" and len(parts) >= 3:
                reader.display_category(parts[1], parts[2])

            elif cmd == "search" and len(parts) >= 2:
                reader.search_symbol(parts[1])

            elif cmd == "export":
                reader.export_to_json()

            else:
                print("[ERROR] Invalid command or missing arguments")

        except KeyboardInterrupt:
            print("\n[INFO] Interrupted by user")
            break
        except Exception as e:
            print(f"[ERROR] {e}")

    print("\n[INFO] Goodbye!")


if __name__ == "__main__":
    main()

